### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by k0chegar** [fengberd/LCScriptEngineTools#1]
Can you explain how to run this script?

![image](https://user-images.githubusercontent.com/77930280/105636754-cdff1700-5e7a-11eb-9f82-3a18d9a8f5fa.png)

I don't understand programming well, maybe I'm doing something wrong?

Thanks!

**Comment by fengberd** [comment]
The command seems to be right, therefore the game might uses a different encryption key.
You should figure out the key by reverse engineering and replace the value of `$_INT_KEY`, `$_SNX_KEY`, `$_FILENAME_KEY`

**Comment by k0chegar** [comment]
I was able to unpack the game file, but this error occurred while packing. I tried to take the game (Mugen Renkan Chijoku ni Mamireshi Fushiki no Rinbu) file based on the program code, but the error is still there.

1)pack
![image](https://user-images.githubusercontent.com/77930280/105719192-11b55780-5f33-11eb-9c86-9ab839842caf.png)
2)unpack
![image](https://user-images.githubusercontent.com/77930280/105719278-2691eb00-5f33-11eb-84cd-1edaf74d41a5.png)

**Comment by fengberd** [comment]
The PHP mbstring extension is missing, enable (or install first) it in `php.ini`

**Comment by k0chegar** [comment]
Thanks for help! Now it works... but If change the text in the "snx files" to Cyrillic, the game crashes.

**Comment by fengberd** [comment]
You must use specified tools to extract & re-import those text instead of editing those snx files directly.
Sorry but this tool doesn't support those features yet, and I have no plan to update it in current.
